volumes:
  dvwa:


networks:
  dvwa:


services:
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx/fullchain.pem:/etc/letsencrypt/live/student19.ppctf.com/fullchain.pem
      - ./nginx/private.pem:/etc/letsencrypt/live/student19.ppctf.com/privkey.pem
      - ./nginx/ssl.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ./nginx/dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem

  nginx_dvwa:
    build: .
    # Change `always` to `build` to build from local source
    pull_policy: always
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    networks:
      - dvwa
    ports:
      - 4280:80
    restart: unless-stopped

  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped

  